version: '3.4'

services:
  albumsandfotos:
    image: albumsandfotos
    container_name: albumsandfotos
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
      SPRING_OPTS: --spring.profiles.active=dev
    ports:
      - 3000:3000
      - 5005:5005

  sonarqube-scanner:
    image: sonarsource/sonar-scanner-cli
    volumes:
      - ./microservice:/proyecto
    working_dir: /proyecto
    environment:
      - SONAR_HOST_URL=http://localhost:9000
    command: -Dsonar.projectKey=albumsandphotos -Dsonar.sources=.

  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
      
  prometheus:
    image: prom/prometheus
    volumes:
      - ./src/test/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - 8081:80
      - 2003-2004:2023-2024
      - 8125:8125/udp

